pipeline {
    agent any

    stages {
        stage('Clean Workspace') {
            steps {
                deleteDir() // Clean the workspace before anything else
            }
        }

        stage('Build') {
            steps {
                sh 'docker build -t my-react:dev ./client'
            }
        }

        stage('Test') {
            steps {
                sh 'docker run --rm my-react:dev npm run test'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run -d -p 5173:5173 my-react:dev'
            }
        }
    }
}